spring.application.name=event_serviceee
# Configuration Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Activer la d�couverte Eureka pour ce service
eureka.client.fetchRegistry=true
eureka.client.registerWithEureka=true
eureka.instance.hostname=localhost

# Configuration Spring Boot (si tu veux configurer un port diff�rent, par exemple)
server.port=8082
